### ISSUE TITLE
test_hocrtransform_matches_sandwich fails

### ISSUE THREAD

**Issue by QuLogic** [jbarlow83/OCRmyPDF#824] opened 2021-09-04 21:40 UTC
**Describe the bug**
I'm not sure if I have a different tesseract version, or something else that produces differences:

```pytb
_____________________ test_hocrtransform_matches_sandwich ______________________
[gw2] linux -- Python 3.10.0 /usr/bin/python3

resources = PosixPath('/builddir/build/BUILD/ocrmypdf-12.4.0/tests/resources')
outdir = PosixPath('/tmp/pytest-of-mockbuild/pytest-0/popen-gw2/test_hocrtransform_matches_san0')

    @pytest.mark.slow
    def test_hocrtransform_matches_sandwich(resources, outdir):
        check_ocrmypdf(resources / 'ccitt.pdf', outdir / 'hocr.pdf', '--pdf-renderer=hocr')
        check_ocrmypdf(
            resources / 'ccitt.pdf', outdir / 'tess.pdf', '--pdf-renderer=sandwich'
        )
    
        def clean(s):
            s = re.sub(r'[ ]+', ' ', s)
            s = re.sub(r'[ ]?[\n]+', r'\n', s)
            return s
    
        hocr_txt = clean(text_from_pdf(outdir / 'hocr.pdf'))
        tess_txt = clean(text_from_pdf(outdir / 'tess.pdf'))
    
        # Path('hocr.txt').write_text(hocr_txt)
        # Path('tess.txt').write_text(tess_txt)
    
>       assert hocr_txt == tess_txt
E       AssertionError: assert '\x0c' == ('The LinnSequencer\n'\n '32 Track MIDI Sequence Recorder\n'\n 'The LinnSequencer is a state-of-the-art composition and performance tool for '\n 'the professional musician. It is\n'\n 'extremely powerful, yet amazingly simple to learn and use. It’s many '\n 'remarkable features include:\n'\n '¢ Operation is similar to multi-track tape recorder with PLAY, STOP, RECORD, '\n 'FAST\n'\n 'FORWARD, REWIND, and LOCATE controls.\n'\n 'e Each of the 100 sequences contains 32 simultaneous, polyphonic tracks. '\n 'Each track may\n'\n 'be assigned to one of 16 MIDI channels. Simultaneously plays up to 16 '\n 'polyphonic\n'\n 'synthesizers!\n'\n '¢ Ultra-fast 3%” disk drive stores complex songs in seconds and holds over '\n '110,000 notes\n'\n '¢ One or all tracks may be TRANSPOSED at the touch of a key.\n'\n 'e Exclusive real-time ERASE function makes editing FAST.\n'\n '* Exclusive REPEAT function automatically repeats any held notes at a '\n 'pre-selected\n'\n 'per disk!\n'\n 'rhythmic value.\n'\n '¢ TIMING CORRECTION works during playback and operates without ‘chopping’ '\n 'notes.\n'\n '¢ Optional SMPTE time code synchronization.\n'\n '© Optional remote control.\n'\n 'Recording a Sequence\n'\n 'To record a sequence, simply press RECORD and PLAY,\n'\n 'then play your MIDI keyboard in time to the Sequencer’s\n'\n 'click track. When the sequence loops back around to bar 1,\n'\n 'you’ ll hear what you played—only all timing errors will be\n'\n 'corrected! (Timing correction may be adjusted or defeated).\n'\n 'Any additional notes played will be added into the track\n'\n '— existing notes are not erased while recording!\n'\n 'FAST FORWARD, REWIND, and LOCATE controls\n'\n 'may be used at any time to quickly access any location in\n'\n 'your sequence for spot-recording. To overdub a new part,\n'\n 'select a different track and start recording—while you\n'\n 'record, the first track will play in perfect sync (unless you\n'\n 'MUTE it, or SOLO another track). In this way, up to 32\n'\n 'tracks may be overdubbed! All MIDI effects are recorded\n'\n 'including pitch bend, modulation, velocity, aftertouch,\n'\n 'sustain pedal, and program changes!\n'\n 'simply use LOCATE, FAST FORWARD, or REWIND to\n'\n 'find the desired bar number, then start recording.\n'\n 'The INSERT/COPY function allows you to move bars\n'\n 'from one location to another—in the same sequence or a\n'\n 'different one. For example, you might insert a copy of the\n'\n 'first verse between the second chorus and the bridge.\n'\n 'DELETE BARS operates the same way to remove\n'\n 'unwanted sections,\n'\n 'Creating a Song\n'\n 'One way to create a song is to record each track all the\n'\n 'way through (up to 999 bars). Another way is to record\n'\n 'each basic section (verse, chorus, etc.) in individual\n'\n 'sequences, then use the CREATE SONG function to “chain”\n'\n 'them together. CREATE SONG will then automatically\n'\n 'copy all the parts into a new sequence. If desired, you can\n'\n 'even set the last few bars to repeat infinitely, for a fadeout.\n'\n 'Editing\n'\n 'Composition Without Compromise\n'\n 'To erase a wrong note, simply hold ERASE and press\n'\n 'the note to be erased just before it plays in the sequence—\n'\n 'when played back, it will be gone. Notes may also be\n'\n 'added, erased, or changed using the SINGLE STEP func-\n'\n 'tion. To overdub notes at specific points within a sequence,\n'\n 'The technology you use should never be so complex that\n'\n 'it interferes with the creative process. That’s precisely why\n'\n 'the LinnSequencer is designed to let you compose, record\n'\n 'and edit while devoting your undivided attention to your\n'\n 'music. See your Linn dealer today for a demonstration!\n'\n 'Additional Features\n'\n '* Simple, easy to learn operation—the 32 character LCD display clearly '\n 'guides you through all operations. If needed, the\n'\n 'HELP button displays additional explanations.\n'\n '* Non-destructive recording—existing notes are not erased while recording.\n'\n '¢ Two FOOTSWITCH INPUTS may be assigned to remotely control many of the '\n 'commonly used functions, including\n'\n 'ERASE, REPEAT, PLAY/STOP, or LOCATE.\n'\n '¢ Iwo TRIGGER OUTPUTS may be programmed to output pulses at any selected '\n 'note value.\n'\n '© Will sync to standard LinnDrum or Linn 9000 sync tone.\n'\n '© Utilizes ultra high-speed, 8 MHz 80186 16 bit computer internally for FAST '\n 'operation.\n'\n '* TEMPO may be specified in BEATS-PER-MINUTE or FRAMES-PER-BEAT at 24, 25, '\n 'or 30 frames per second,\n'\n '¢ TEMPO may be entered numerically, adjustable in tenths of a '\n 'Beat-Per-Minute increments, or by tapping quarter notes\n'\n '(even drop frame!)\n'\n 'on the TAP TEMPO button.\n'\n '¢ TEMPO CHANGES may be programmed into a sequence, with smooth transitions '\n 'if desired.\n'\n '¢ Any TIME SIGNATURE may be used, and may be changed within a song.\n'\n 'linn\n'\n 'Linn Electronics, Inc.\n'\n '18720 Oxnard Street, Tarzana, CA 91356\n'\n '(818) 708-8131 TELEX #298949 LINN UR\n'\n '\x0c')
E         Strings contain only whitespace, escaping them using repr()
E         - 'The LinnSequencer\n32 Track MIDI Sequence Recorder\nThe LinnSequencer is a state-of-the-art composition and performance tool for the professional musician. It is\nextremely powerful, yet amazingly simple to learn and use. It’s many remarkable features include:\n¢ Operation is similar to multi-track tape recorder with PLAY, STOP, RECORD, FAST\nFORWARD, REWIND, and LOCATE controls.\ne Each of the 100 sequences contains 32 simultaneous, polyphonic tracks. Each track may\nbe assigned to one of 16 MIDI channels. Simultaneously plays up to 16 polyphonic\nsynthesizers!\n¢ Ultra-fast 3%” disk drive stores complex songs in seconds and holds over 110,000 notes\n¢ One or all tracks may be TRANSPOSED at the touch of a key.\ne Exclusive real-time ERASE function makes editing FAST.\n* Exclusive REPEAT function automatically repeats any held notes at a pre-selected\nper disk!\nrhythmic value.\n¢ TIMING CORRECTION works during playback and operates without ‘chopping’ notes.\n¢ Optional SMPTE time code synchronization.\n© Optional remote control.\nRecording a Sequence\nTo record a sequence, simply press RECORD and PLAY,\nthen play your MIDI keyboard in time to the Sequencer’s\nclick track. When the sequence loops back around to bar 1,\nyou’ ll hear what you played—only all timing errors will be\ncorrected! (Timing correction may be adjusted or defeated).\nAny additional notes played will be added into the track\n— existing notes are not erased while recording!\nFAST FORWARD, REWIND, and LOCATE controls\nmay be used at any time to quickly access any location in\nyour sequence for spot-recording. To overdub a new part,\nselect a different track and start recording—while you\nrecord, the first track will play in perfect sync (unless you\nMUTE it, or SOLO another track). In this way, up to 32\ntracks may be overdubbed! All MIDI effects are recorded\nincluding pitch bend, modulation, velocity, aftertouch,\nsustain pedal, and program changes!\nsimply use LOCATE, FAST FORWARD, or REWIND to\nfind the desired bar number, then start recording.\nThe INSERT/COPY function allows you to move bars\nfrom one location to another—in the same sequence or a\ndifferent one. For example, you might insert a copy of the\nfirst verse between the second chorus and the bridge.\nDELETE BARS operates the same way to remove\nunwanted sections,\nCreating a Song\nOne way to create a song is to record each track all the\nway through (up to 999 bars). Another way is to record\neach basic section (verse, chorus, etc.) in individual\nsequences, then use the CREATE SONG function to “chain”\nthem together. CREATE SONG will then automatically\ncopy all the parts into a new sequence. If desired, you can\neven set the last few bars to repeat infinitely, for a fadeout.\nEditing\nComposition Without Compromise\nTo erase a wrong note, simply hold ERASE and press\nthe note to be erased just before it plays in the sequence—\nwhen played back, it will be gone. Notes may also be\nadded, erased, or changed using the SINGLE STEP func-\ntion. To overdub notes at specific points within a sequence,\nThe technology you use should never be so complex that\nit interferes with the creative process. That’s precisely why\nthe LinnSequencer is designed to let you compose, record\nand edit while devoting your undivided attention to your\nmusic. See your Linn dealer today for a demonstration!\nAdditional Features\n* Simple, easy to learn operation—the 32 character LCD display clearly guides you through all operations. If needed, the\nHELP button displays additional explanations.\n* Non-destructive recording—existing notes are not erased while recording.\n¢ Two FOOTSWITCH INPUTS may be assigned to remotely control many of the commonly used functions, including\nERASE, REPEAT, PLAY/STOP, or LOCATE.\n¢ Iwo TRIGGER OUTPUTS may be programmed to output pulses at any selected note value.\n© Will sync to standard LinnDrum or Linn 9000 sync tone.\n© Utilizes ultra high-speed, 8 MHz 80186 16 bit computer internally for FAST operation.\n* TEMPO may be specified in BEATS-PER-MINUTE or FRAMES-PER-BEAT at 24, 25, or 30 frames per second,\n¢ TEMPO may be entered numerically, adjustable in tenths of a Beat-Per-Minute increments, or by tapping quarter notes\n(even drop frame!)\non the TAP TEMPO button.\n¢ TEMPO CHANGES may be programmed into a sequence, with smooth transitions if desired.\n¢ Any TIME SIGNATURE may be used, and may be changed within a song.\nlinn\nLinn Electronics, Inc.\n18720 Oxnard Street, Tarzana, CA 91356\n(818) 708-8131 TELEX #298949 LINN UR\n\x0c'
E         + '\x0c'

tests/test_hocrtransform.py:82: AssertionError
----------------------------- Captured stderr call -----------------------------
Scanning contents: 100%|██████████| 1/1 [00:00<00:00, 23.35page/s]
OCR: 100%|██████████| 1.0/1.0 [01:13<00:00, 73.88s/page] 
PDF/A conversion: 100%|██████████| 1/1 [00:00<00:00, 25.85page/s]
JPEGs: 0image [00:00, ?image/s]
JBIG2: 0item [00:00, ?item/s]
Scanning contents: 100%|██████████| 1/1 [00:00<00:00, 33.68page/s]
OCR: 100%|██████████| 1.0/1.0 [00:25<00:00, 25.75s/page]
PDF/A conversion: 100%|██████████| 1/1 [00:00<00:00,  5.09page/s]
JPEGs: 0image [00:00, ?image/s]
JBIG2: 0item [00:00, ?item/s]
```

**To Reproduce**
Run pytest

**System (please complete the following information):**
 - OS: Fedora Rawhide
 - Python version: 3.10.0rc1
 - OCRmyPDF version: 12.4.0

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip?
Building package from source

**Comment by jbarlow83** [comment] 2021-09-26 07:03
Duplicate of #828

**Closed by jbarlow83** 2021-09-26 07:03 UTC
