### ISSUE TITLE
run_pipeline() missing 1 required positional argument: 'options'

### ISSUE THREAD

**Issue by blubbsy** [jbarlow83/OCRmyPDF#475] opened 2020-01-08 09:23 UTC
**Describe the issue**
When running Debian Bullseye "ocrmypdf -h" (or any other combination" i receive the following error:
TypeError: run_pipeline() missing 1 required positional argument: 'options'

I couldnt find out why it fails directly when executing. If there is not a known reason for the rror i will go and install it manually (to get the newer version) and try it again, but until then i will keep the issue as it is. 

**To Reproduce**
``` bash
sudo apt install ocrmypdf
ocrmypdf -h
```

**Expected behavior**
Returning the help information or executing the error command. 

**System:**

- OS:
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        8.11
Codename:       jessie
- OCRmyPDF Version: 9.1.0+dfsg-1

**Comment by jbarlow83** [comment] 2020-01-09 20:50
I could not reproduce this with the Docker versions of Debian sid or bullseye. It does not occur after a clean install.

About 9 months ago the entry point of the application was renamed from `run_pipeline()` to `run()`. The fact that your system is trying to find `run_pipeline()` suggests there's an older version of ocrmypdf installed on the system (older than v9.0). Perhaps installed with pip or left over from a Debian system upgrade. Try `which ocrmypdf` and `cat $(which ocrmypdf)` to see what the `ocrmypdf` entry script is doing, and remove the old installation.

**Comment by jbarlow83** [comment] 2020-01-09 20:50
I'll close the issue now. If you have further related questions feel free to reopen it.

**Closed by jbarlow83** 2020-01-09 20:50 UTC
Labels: user config
