### ISSUE TITLE
Feature request, recognize words on a line as a continuous phrase.

### ISSUE THREAD

**Issue by chris001** [jbarlow83/OCRmyPDF#133] opened 2017-02-07 21:32 UTC
Inside a pdf viewer (acrobat reader, or pdf.js in the browser), you cannot search for a phrase of multiple words.  The phrase matches nothing even when it is in the document.

# Bug report / Feature request
## Expected Behavior

When the document contains, for example, "Breakfast menu", when you click the search icon (magnifying glass) in pdf.js browser pdf viewer, and enter text "breakfast menu", it should match the text and find it.

## Current Behavior

It only matches one word. For example, it matches "breakfast", or it matches "menu".  If you try to search for two words "breakfast menu", it fails to find a match, even when the two words are clearly together on the same line, in the document!

## Possible Solution

Possibly take a look at the parameters or settings see if it can be made to connect words which are on the same line, into the same continuous text line.

## Steps to Reproduce (for bugs)

1. Run the ocr on a pdf file containing scanned images of pages.
3. Open the output pdf file which contains the recognized text, in the browser pdf.js viewer.
4. Click the magnifying glass, enter text for two adjacent words on the same line.  Search fails to find the two words.  It finds only one word at a time.

## Context

Searching for only one word at a time is awkward and time consuming.

## Your Environment

* OCR version used:  Latest
* Operating System and version (desktop or mobile): Windows 10, Linux Debian 8.
* PHP version 7.0

**Comment by jbarlow83** [comment] 2017-02-10 17:15
Thanks for the detailed report.

Try using the settings `--pdf-renderer tesseract --output-type pdf`.

PDFs have no concept of words and lines internally (except for accessibility Tagged PDFs). It is a page description format that looks like "move the cursor here, draw a glyph, move somewhere else, draw another one". Improvements can be made, but this can't always be done exactly.

**Comment by chris001** [comment] 2017-02-10 21:08
Thanks @jbarlow83 for the settings, tried them and got the same result as before, search only works when you search for one word, two-word searches are not found.  This is a problem when trying to search for documents containing two very common dictionary words in series.  For example, "breakfast menu".  Suppose there are 500 documents containing the word breakfast, and 400 documents containing the word "menu".  But only 10 documents contain the sequence of words, "breakfast menu".  You would have to open and read every one of the 400 documents containing the word "menu" to manually search for the documents containing the two word sequence "breakfast menu".

**Comment by jbarlow83** [comment] 2017-02-10 21:27
I wasn't denying that the feature is useful. I was explaining that the behavior of search strongly 
depends on both the internal formatting of the PDF and the PDF viewer. I have no control over how a PDF viewer decides that two words are adjacent. It does work on many files.

What PDF viewers are you using?

If you send me a sample I may be able to see if there's something unusual going on.

**Comment by chris001** [comment] 2017-02-11 01:19
Good idea, just tried the search inside the full acrobat reader app, and searching for two words in a row works.  Guess the `pdf.js` viewer is limited to searching for one word at a time!

**Comment by femifrak** [comment] 2017-02-17 07:45
This issue seems to be related to [https://github.com/fritz-hh/OCRmyPDF/issues/66](https://github.com/fritz-hh/OCRmyPDF/issues/66)
and to [https://github.com/fritz-hh/OCRmyPDF/issues/64](https://github.com/fritz-hh/OCRmyPDF/issues/64)
and maybe to #5 as well.

Long time ago, fritz-hh said:

>Tesseract returns both bounding boxes for each word and for each lines, but it was a design desicion to print the words separately in OCRmypDF rather than full lines of words connected with blank:


If it is really a design decision, would it be possible to implement the "line option" additionally to the "word option"?

**Comment by jbarlow83** [comment] 2017-02-17 09:05
@femifrak That comment only applies to the hocr PDF renderer which is the safe but dumb default at the moment. As in it basically works on with Latin alphabets. I offer tesseract's PDF renderer as an option as well. I see that as the future and I work with the tesseract people on improving it. It has some compatibility problems still, so it's not the default, but when it works it's a lot better. I'm not saying I'd never look at improving the hocr renderer, but it's not a high priority. I don't think the "line option" would make a big difference; it would depend on how reportlab implements it. Contributions and improvements are always welcome.

As @chris001 found the problem is the same whether the hocr or tesseract renderer were used. Because they are so different in how they function, it sounds like the issue is with pdf.js. (Of course, it would help to see the file.)

**Comment by chris001** [comment] 2017-02-18 08:00
Here's a page of scanned printed text - the back of a CD box - to demonstrates how ocrmypdf produces text which the full acrobat reader app can search for multiple consecutive words, while the `pdf.js` in firefox is only able to find one word per search.
[scan0388_OCR.pdf](https://github.com/jbarlow83/OCRmyPDF/files/784865/scan0388_OCR.pdf)

**Comment by jbarlow83** [comment] 2017-02-18 08:28
You're using Tesseract 3.03 which has several PDF compatibility problems compared to 3.04. In particular it will also have problems on mobile and macOS Preview.app.

I redid OCR in Tesseract 4.00alpha using the ocrmypdf-tess4 docker image with ``--pdf-renderer tess4 --output-type pdf``. [scan0388_ocrt4.pdf](https://github.com/jbarlow83/OCRmyPDF/files/784872/scan0388_ocrt4.pdf)

It works well in everything except pdf.js, so it looks like the issue likes with their implementation of word break parsing. They have [63 open issues](https://github.com/mozilla/pdf.js/issues?q=is%3Aopen+is%3Aissue+label%3A4-text-selection) related to text selection and from my perusal the way they handle it currently is quite naïve.

**Comment by jbarlow83** [comment] 2017-02-18 08:34
It may be a pain to get a newer Tesseract onto Debian 8. I think the best option for PDF viewer compatibility is to use ocrmypdf and the default pdf-renderer (hocr) and output type.

I'm going to close this for now as I don't think there's anything I can do to improve text selection with pdf.js.

**Closed by jbarlow83** 2017-02-18 08:34 UTC
