### ISSUE TITLE
Partially searchable pdfs

### ISSUE THREAD

**Issue by MislavSag** [jbarlow83/OCRmyPDF#313] opened 2018-11-13 09:39 UTC
I have two short questions on new issue of the package.

1. If I get it right it would not be possible to use the package with Python 3.x after the release 8.x?
2. Is it now possible to somehow recognize what is the "quality" of text in existing document? Right now I am using --force-ocr option, even on fully searchable documents since it is very difficult to estimate which are fully readable, which are not readable at all and which are partially readable. Is it possible to somehow set threshold above which I would like to use --force-ocr?

**Comment by jbarlow83** [comment] 2018-11-13 10:10
Python 3.5 support will be dropped in ocrmypdf 8.x. Python 3.6 and 3.7 will continue to work. Basically, I put the notice there to see if anyone complains, which would indicate to me that it is worth supporting 3.5 after all. Likewise I will drop Tesseract 3.x support since 4.x is out now.

For the second question, have a look at the explanation of different OCR modes:
https://ocrmypdf.readthedocs.io/en/latest/advanced.html#when-ocr-is-skipped
You can let ocrmypdf skip OCR for fully searchable pages, or search for additional text in images with --redo-ocr (redo also adds OCR if all text was printable in the first place). Avoid --force-ocr if possible.

If you want to assess OCR quality, meaning the accuracy of Tesseract, then you need ground truth; you need some information that is known to be 100% accurate to compare against. Then run Tesseract and compare the OCR output (in the --sidecar file for example) and see if it matches the ground truth file.

**Comment by MislavSag** [comment] 2018-11-13 12:56
Thanks for detailed explanation. 

--redo-ocr is exatly what I need. As I understand it avoids searchable part of text.

Thanks!

**Comment by MislavSag** [comment] 2018-11-14 09:56
I have pulled latest version of image `docker pull jbarlow83/ocrmypdf-polyglot` and tried to add --redo-ocr option, but it doesn't work. It works with --skip-text and --force-ocr.

What can be a problem?

**Comment by jbarlow83** [comment] 2018-11-19 08:06
I'll close the issue now. If you have further related questions feel free to reopen it.

**Closed by jbarlow83** 2018-11-19 08:06 UTC

**Comment by jbarlow83** [comment] 2018-12-19 23:02
I apologize for closing without notice your final question. Just in case you were still having trouble, the Docker autobuild for ocrmypdf-polyglot image was broken at that time, so pulling fetched an older version. The issue is now fixed.
