### ISSUE TITLE
Problem in detecting resolution

### ISSUE THREAD

**Issue by christian-oreilly** [jbarlow83/OCRmyPDF#97] opened 2016-09-30 18:01 UTC
Using the regular command

ocrmypdf input.pdf output.pdf

I got

['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-sDEVICE=pngmono', '-dFirstPage=1', '-dLastPage=1', '-o', '/tmp/tmpbqf_b27a', '-r0.0x0.0', '/tmp/com.github.ocrmypdf.uwmb9n6x/000001.ocr.oriented.pdf']

Note the zero resolution. I searched for the source of the error. I found in the pageinfo.py file, in the _find_page_regular_images(...) function that the loop "for raster in contentsinfo.raster_settings:" (line 285) will never compute the resolution because because it always enters in the if clause at line 290 (if raster.stack_depth == 0:) ... 

I'm not sure to understand the comment explaining the purpose of this if clause... but commenting it out fixed the issue in my case... without generating any extravagant DPI (~300 DPI). I'm not sure if there is anything "exotic" in the PDF I'm processing. Unfortunately, I cannot share it publicly (it is copyrighted material) but I can send it in private in case of need.

I would suggest replacing 

```
        if raster.stack_depth == 0:
            continue

        dpi_w, dpi_h = _get_dpi(raster.shorthand, (image['width'], image['height']))
```

by

```
        dpi_w, dpi_h = _get_dpi(raster.shorthand, (image['width'], image['height']))
        dpi_w = min(dpi_w , MAX_DPI)
        dpi_h = min(dpi_h, MAX_DPI)
```

with MAX_DPI being a resonable constant... 600? Is there any reason to OCR document at more than 600 DPI? Anyway, any reasonable value...

**Comment by jbarlow83** [comment] 2016-10-05 21:06
When the stack depth of the transformation is zero, the PDF is asking for an image to be drawn in a 1/72" square in the bottom left corner of the page. That usually means the software that created the PDF is doing something incorrectly.

Of course your proposed change is quite reasonable, but there's other PDFs with this problem where the best course of action was to ignore these images. Please send me the file so I can take a look.

**Comment by jbarlow83** [comment] 2017-02-07 05:42
It's also possible that commit 1976dc6f3 fixed this issue, as before that fix the stack depth could lose sync with reality due to a problem in PyPDF2.

I'm going to close it for now because I've made two related fixes in this area and I don't have a test file to confirm. If the issue is not still resolved, please let me know.

**Closed by jbarlow83** 2017-02-07 05:42 UTC
