### ISSUE TITLE
OSError: cannot load library 'C:\Program Files\Tesseract-OCR\liblept-5.dll': error 0x7e

### ISSUE THREAD

**Issue by meet1919** [jbarlow83/OCRmyPDF#833] opened 2021-09-15 14:35 UTC
As in [#631 ](https://github.com/jbarlow83/OCRmyPDF/issues/631) I am getting the same error. Instead of `0x7f` I am getting `0x7e`  
I am using Python 3.9.2 64 bit, Windows 10 64 bit and OCRMYPDF = 12.5.0
I cant solve the problem as solved #631 by changing `leptonica.py`, that is by opening `zlib.dll` before `liblept-5.dll`.

When I run the code `ocrmypdf --help` or `ocrmypdf --version` it displays same OSerror.

Does anyone know what to do?  @jbarlow83

**Comment by jbarlow83** [comment] 2021-09-16 08:53
Is Tesseract also 64 bit?

**Comment by meet1919** [comment] 2021-09-16 09:22
> Is Tesseract also 64 bit?

Yes, it is 64 bit. Earlier when I first tried using ocrmypdf, tesseract 5.0.0 Alpha was installed. I thought maybe there might be a problem with tesseract itself. I uninstalled and installed tesseract 4.1.0 to check whether it's working. But still this OSError comes.
I don't know much but 0x7e is something related corrupt files or something like that.

**Comment by meet1919** [comment] 2021-09-17 09:16
@jbarlow83  ??????

**Comment by jbarlow83** [comment] 2021-09-17 09:40
You could try a source install of ocrmypdf, run `python src/ocrmypdf/lib/compile_leptonica.py`, to see if rebuild the cffi bindings helps. Also ensure `cffi` is the latest version.

It may be a few days before I have a chance to look into this.

**Comment by meet1919** [comment] 2021-09-18 06:11
Thank you for the support but Rebuilding cffi bindings didn't work.

**Comment by meet1919** [comment] 2021-09-18 06:51
is there any other library for loading dll files other than cffi?

**Comment by jbarlow83** [comment] 2021-09-18 07:09
Yes, but it would require rewriting that module.

FWIW I am hoping to eliminate the leptonica.py module somehow, so I'm hoping to find ways for it to limp along rather save it.

**Comment by jbarlow83** [comment] 2021-09-19 06:47
I installed tesseract v5.0.0-alpha.20210811 (which includes leptonica-1.78.0) using `choco` (chocolatey), and ocrmypdf 12.5.0, and I cannot reproduce this issue. Installed on a Windows 10 20H2 virtual machine. For sanity I confirmed that all tests pass as well.

I was using Python 3.9.6.

Are you using Microsoft Store Python or Python.org Python? The former can cause problems.

What's the exact version of Tesseract and Leptonica you have installed?

**Comment by meet1919** [comment] 2021-09-19 09:30
I upgraded python to 3.9.7, tesseract and ocrmypdf (12.5.0)
Below is the output of `pytesseract.get_tesseract_version()`

`5.0.0-alpha.20210811
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found libarchive 3.5.0 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6 liblz4/1.7.5 libzstd/1.4.5
 Found libcurl/7.77.0-DEV Schannel zlib/1.2.11 zstd/1.4.5 libidn2/2.0.4 nghttp2/1.31.0
`
Below is the error :

`(mir) PS C:\Users\meetg\PycharmProjects\python\Miracle\ocrmypdf> ocrmypdf dm6.pdf output.pdf

Traceback (most recent call last):
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\lib\runpy.py", line 87, in _run_code
  File "C:\Users\meetg\PycharmProjects\python\Miracle\mir\Scripts\ocrmypdf.exe\__main__.py", line 4, in <module>
  File "C:\Users\meetg\PycharmProjects\python\Miracle\mir\lib\site-packages\ocrmypdf\__init__.py", line 10, in <module>
    from ocrmypdf import helpers, hocrtransform, leptonica, pdfa, pdfinfo
  File "C:\Users\meetg\PycharmProjects\python\Miracle\mir\lib\site-packages\ocrmypdf\leptonica.py", line 82, in <module>
    lept = ffi.dlopen(_libpath)
OSError: cannot load library 'C:\Program Files\Tesseract-OCR\liblept-5.dll': error 0x7e`

**Comment by jbarlow83** [comment] 2021-10-16 07:17
I'm assuming this is related to Microsoft Store Python & closing the issue unless further information is available.
We regularly test on Python for Windows.

**Closed by jbarlow83** 2021-10-16 07:17 UTC

**Comment by seanbenhur** [comment] 2021-11-11 05:52
I am still getting this issue, is there any workaround for this?

**Comment by mara004** [comment] 2021-11-11 10:45
@seanbenhur Have you made sure you are not using the Python from Microsoft Store (in best case uninstalled it)?

**Comment by seanbenhur** [comment] 2021-11-11 10:45
Yes, I am using standard python

**Comment by mara004** [comment] 2021-11-11 10:47
Could you please paste the traceback?

**Comment by seanbenhur** [comment] 2021-11-11 10:51
Update, I fixed it by installing previous version` ocrmypdf 11.0`

**Comment by seanbenhur** [comment] 2021-11-12 03:45
So, in 11.0 I get ghostscript missing dependency error, even if it is installed and set to Path, but when I switch to 12.2.0, I get this dll error. Here is my traceback
```
D:\invoicenet>python test_flask_base64.py
Traceback (most recent call last):
  File "test_flask_base64.py", line 15, in <module>
    import ocrmypdf
  File "C:\Users\lokesh.natarajan\AppData\Local\Programs\Python\Python37\lib\site-packages\ocrmypdf\__init__.py", line 10, in <module>
    from ocrmypdf import helpers, hocrtransform, leptonica, pdfa, pdfinfo
  File "C:\Users\lokesh.natarajan\AppData\Local\Programs\Python\Python37\lib\site-packages\ocrmypdf\leptonica.py", line 81, in <module>
    lept = ffi.dlopen(_libpath)
OSError: cannot load library 'C:\Program Files\Tesseract-OCR\liblept-5.dll': error 0x7e
```

**Comment by mara004** [comment] 2021-11-12 11:42
How confusing. Are your Python and Tessearct both 64-bit?
Concerning the ghostscript issue: can you paste the content of your `%PATH%` variable?

**Comment by seanbenhur** [comment] 2021-11-12 12:23
Yes, both my python and tesseract are 64 bit
I installed both manually

My path variable
```
D:\invoicenet>echo %PATH%
C:\Program Files\gs\gs9.55.0\bin;C:\Python310\Scripts\;C:\Python310\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\GTK3-Runtime Win64\bin;C:\Users\lokesh.natarajan\Downloads\chromedriver_win32\chromedriver.exe;C:\Program Files\nodejs\;C:\Program Files\gs\gs9.55.0\bin;C:\ProgramData\chocolatey\bin;C:\Users\lokesh.natarajan\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\lokesh.natarajan\AppData\Local\Programs\Python\Python37\;C:\Users\lokesh.natarajan\miniconda3;C:\Users\lokesh.natarajan\miniconda3\Library\mingw-w64\bin;C:\Users\lokesh.natarajan\miniconda3\Library\usr\bin;C:\Users\lokesh.natarajan\miniconda3\Library\bin;C:\Users\lokesh.natarajan\miniconda3\Scripts;C:\Users\lokesh.natarajan\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\lokesh.natarajan\AppData\Local\Programs\Python\Python39\;C:\Users\lokesh.natarajan\AppData\Local\Microsoft\WindowsApps;C:\Users\lokesh.natarajan\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\lokesh.natarajan\AppData\Roaming\npm;C:\Program Files\gs\gs9.55.0\bin;C:\Program Files\Tesseract-OCR;
```

**Comment by mara004** [comment] 2021-11-12 13:28
The ghostscript folder `C:\Program Files\gs\gs9.55.0\bin` seems to be contained 3 times in your `%PATH%` ... ?

**Comment by seanbenhur** [comment] 2021-11-12 14:23
Yeah, cause I have added that many times since the issue said, that
ghostscript is not in the path

**Comment by mara004** [comment] 2021-11-12 15:20
What is the name of the ghostscrpit binary in your `C:\Program Files\gs\gs9.55.0\bin` install?
ocrmypdf searches for an executable named `gswin64c` or `gswin32c`:https://github.com/jbarlow83/OCRmyPDF/blob/8be9a68c5e9b6a110cfe37f145b70829540f5099/src/ocrmypdf/_exec/ghostscript.py#L39

**Comment by seanbenhur** [comment] 2021-11-13 06:18
Yeah, it has same filename gswin64

**Comment by jbarlow83** [comment] 2021-11-13 09:24
The next major release will eliminate the dependency on leptonica/liblept because it's a longstanding source of pain for Windows and macOS users. I'm testing it now.

**Comment by seanbenhur** [comment] 2021-11-13 10:31
Great, when can we expect the new version?
Thanks a lot for your help!

**Comment by jbarlow83** [comment] 2021-11-13 20:43
Try `pip install --upgrade --user --pre ocrmypdf` to get the pre-release.

**Comment by seanbenhur** [comment] 2021-11-15 03:22
Thanks, but I got a different issue now
```

Traceback (most recent call last):
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\invoicenet\test_flask_base64.py", line 228, in upload_file
    convert_scanned_and_save(app.config['TABLE_DIR'], app.config['TABLE_NATIVE_PDFS_DIR'])
  File "D:\invoicenet\test_flask_base64.py", line 141, in convert_scanned_and_save
    convert_scanned_to_native(filename,pdf_path)
  File "D:\invoicenet\test_flask_base64.py", line 127, in convert_scanned_to_native
    remove_background=True,language="eng", deskew=True, force_ocr=True)
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\ocrmypdf\api.py", line 335, in ocr
    check_options(options, plugin_manager)
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\ocrmypdf\_validation.py", line 271, in check_options
    ocr_engine_languages = plugin_manager.hook.get_ocr_engine().languages(options)
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\ocrmypdf\builtin_plugins\tesseract_ocr.py", line 135, in languages
    return tesseract.get_languages()
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\ocrmypdf\_exec\tesseract.py", line 108, in get_languages
    check=True,
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\ocrmypdf\subprocess\__init__.py", line 47, in run
    args, env, process_log, _text = _fix_process_args(args, env, kwargs)
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\ocrmypdf\subprocess\__init__.py", line 115, in _fix_process_args
    args = fix_windows_args(program, args, env)
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\ocrmypdf\subprocess\_windows.py", line 131, in fix_windows_args
    shimmed_path = shim_path(shim, env)
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\ocrmypdf\subprocess\_windows.py", line 105, in shim_path
    return os.pathsep.join(str(p) for p in new_paths(env) if p)
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\ocrmypdf\subprocess\_windows.py", line 105, in <genexpr>
    return os.pathsep.join(str(p) for p in new_paths(env) if p)
  File "C:\Users\lokesh.natarajan\AppData\Roaming\Python\Python37\site-packages\ocrmypdf\subprocess\_windows.py", line 54, in registry_path_ghostscript
    latest_gs = max(registry_subkeys(k), key=LooseVersion)
ValueError: max() arg is an empty sequence
```

**Comment by seanbenhur** [comment] 2021-11-15 03:42
Update: The issue is fixed by navigating to the file and changing from  `latest_gs = max(registry_subkeys(k), key=LooseVersion)` to `latest_gs = max(registry_subkeys(k), key=LooseVersion, default=0) `and then remove_background is also set to False, Thanks a lot @mara004  and @jbarlow83  for the help!
