### ISSUE TITLE
No such File or directory: 'tesseract'

### ISSUE THREAD

**Issue by betuxy** [jbarlow83/OCRmyPDF#772] opened 2021-04-30 17:53 UTC
**Describe the bug**
I installed ocrmypdf systemwide via pip as there is no package for voidlinux yet.
Tesseract is to be found under /usr/bin/tesseract-ocr. 
However the program seems to be looking for tesseract only, which is its name on some distros.
I don't know if it has been discussed already but I couldn't find a corresponding ticket.

I solved the problem by creating a Symlink from tesseract-ocr to tesseract, but was wondering if this is something worth changing in code.

**Traceback**
Traceback (most recent call last):
  File "/usr/bin/ocrmypdf", line 8, in <module>
    sys.exit(run())
  File "/usr/lib/python3.9/site-packages/ocrmypdf/__main__.py", line 57, in run
    check_options(options, plugin_manager)
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_validation.py", line 270, in check_options
    ocr_engine_languages = plugin_manager.hook.get_ocr_engine().languages(options)
  File "/usr/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/tesseract_ocr.py", line 136, in languages
    return tesseract.get_languages()
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_exec/tesseract.py", line 102, in get_languages
    proc = run(
  File "/usr/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 51, in run
    proc = subprocess_run(args, env=env, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tesseract'

**System (please complete the following information):**
 - OS: Void Linux
 - Python version: 3.9.4
 - OCRmyPDF version: 12.0.0

**Comment by jbarlow83** [comment] 2021-05-02 07:27
I respectfully submit that the issue is with Void Linux and should be fixed there. It has renamed a widely used executable, `tesseract`, to something that is not standard on, to my knowledge: all other Linux distributions, Windows, macOS and BSD.

As you have pointed out, there is a simple workaround.

**Closed by jbarlow83** 2021-05-02 07:27 UTC
Labels: third party issue
