### ISSUE TITLE
OCRmyPDF crashes on certain PDF documents while trying to access 'userunit' on None.

### ISSUE THREAD

**Issue by jonaswinkler** [jbarlow83/OCRmyPDF#700] opened 2020-12-23 19:18 UTC
**Describe the bug**

On certain documents, we're getting uncaught exceptions from OCRmyPDF when using the --redo option.

```
17:59:28 [Q] ERROR Failed [example.pdf] - 'NoneType' object has no attribute 'userunit' : Traceback (most recent call last):
File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 216, in parse
ocrmypdf.ocr(**ocr_args)
File "/usr/local/lib/python3.7/site-packages/ocrmypdf/api.py", line 316, in ocr
return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
File "/usr/local/lib/python3.7/site-packages/ocrmypdf/_sync.py", line 366, in run_pipeline
validate_pdfinfo_options(context)
File "/usr/local/lib/python3.7/site-packages/ocrmypdf/_pipeline.py", line 177, in validate_pdfinfo_options
if pdfinfo.has_userunit and options.output_type.startswith('pdfa'):
File "/usr/local/lib/python3.7/site-packages/ocrmypdf/pdfinfo/info.py", line 840, in has_userunit
return any(page.userunit != 1.0 for page in self.pages)
File "/usr/local/lib/python3.7/site-packages/ocrmypdf/pdfinfo/info.py", line 840, in
return any(page.userunit != 1.0 for page in self.pages)
AttributeError: 'NoneType' object has no attribute 'userunit'
```

The actual document in question is a document with no embedded text. It is a confidential document and cannot be shared, sadly. The full command line used is as follows

`--input-file example.pdf --output-file archive.pdf --use-threads --jobs 2 --language eng --output-type pdfa --clean --redo-ocr`

We're using the API, but calling OCRmyPDF with these arguments on the command line gives the same results.

Also see the issue over here: https://github.com/jonaswinkler/paperless-ng/issues/180

**Expected behavior**
If this is an issue with the PDF document, I'd expect an exception stating what the issue is. If its an issue with OCRmyPDF, I'd expect OCRmyPDF to properly process the file.

 - OS: Debian Buster
 - OCRmyPDF Version: 11.3.4
 - How did you install ocrmypdf? pip

**Comment by kylebavis** [comment] 2020-12-23 19:26
Output with -v1:

```
ocrmypdf 11.4.1
Running: ['tesseract', '--list-langs']
stdout/stderr = List of available languages (3):
eng
osd
snum

Running: ['unpaper', '--version']
Found unpaper 6.1
Running: ['tesseract', '--version']
Found tesseract 4.1.1
Running: ['tesseract', '-l', 'eng', '--print-parameters', 'pdf']
Running: ['gs', '--version']
Found gs 9.53.3
pikepdf mmap disabled
os.symlink(example.pdf, /var/folders/y4/025h5khs0jgd77pnkz709yyw0000gn/T/ocrmypdf.io.ihgckhke/origin)
os.symlink(/var/folders/y4/025h5khs0jgd77pnkz709yyw0000gn/T/ocrmypdf.io.ihgckhke/origin, /var/folders/y4/025h5khs0jgd77pnkz709yyw0000gn/T/ocrmypdf.io.ihgckhke/origin.pdf)
pikepdf mmap disabled
Scanning contents:   7%|██████▌                                                                                            | 2/30 [00:00<00:02, 11.06page/s]
An exception occurred while executing the pipeline
Traceback (most recent call last):
  File "/usr/local/Cellar/ocrmypdf/11.4.1/libexec/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 366, in run_pipeline
    validate_pdfinfo_options(context)
  File "/usr/local/Cellar/ocrmypdf/11.4.1/libexec/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 178, in validate_pdfinfo_options
    if pdfinfo.has_userunit and options.output_type.startswith('pdfa'):
  File "/usr/local/Cellar/ocrmypdf/11.4.1/libexec/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 845, in has_userunit
    return any(page.userunit != 1.0 for page in self.pages)
  File "/usr/local/Cellar/ocrmypdf/11.4.1/libexec/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 845, in <genexpr>
    return any(page.userunit != 1.0 for page in self.pages)
AttributeError: 'NoneType' object has no attribute 'userunit'
```
It looks like it's failing on the second page, which is totally blank. If I remove that page from the document it runs without issue.

**Comment by jbarlow83** [comment] 2020-12-25 08:00
Can you run `qpdf --json offendingfile.pdf` and upload the results here? The qpdf json descriptions structural information about the PDF without revealing its contents. It's unclear to me in what way this file is damaged.

**Comment by kylebavis** [comment] 2020-12-25 16:14
[output.txt](https://github.com/jbarlow83/OCRmyPDF/files/5742175/output.txt)

**Comment by jbarlow83** [comment] 2020-12-29 10:18
This one is really odd. output.txt shows no issues I can see concerning page 2. I can reproduce this but forcing what looks like an impossible result (there'd be an exception), and I can't seem to reproduce it by corrupting various parameters of page. (It's not just a matter of patching that one line; that's just the first of many errors.)

Might be worth checking if `qpdf input.pdf output.pdf; ocrmypdf output.pdf ...` fixes the issue, or if dropping `--use-threads --jobs 2` has any effect.

If you're able to encrypt the file for me and share it perhaps that would help.

**Comment by kylebavis** [comment] 2020-12-29 17:12
Running ocrmypdf without `--use-threads --jobs 2` doesn't change the behavior.

Using qpdf first as you suggest does work - ocrmypdf processes the resultant document without any errors. 

I took a second look at the batch of documents I've been working with where this issue presented itself; one of them doesn't have anything especially sensitive in it (basically just a privacy policy with no PII in it), so I'd be ok with sharing it. I'd prefer to not upload it publicly, but if you give me an email address or some other way to send you a download link privately, I can send you a copy of it to inspect.

**Comment by jbarlow83** [comment] 2020-12-31 10:58
Thanks that should be much easier.

You can encrypt it with my public key as described here:
https://github.com/jbarlow83/OCRmyPDF/wiki

Or email your link to james@purplerock.ca

**Comment by jbarlow83** [comment] 2021-01-01 09:37
Thanks, reproduced it finally. ocrmypdf was unintentionally suppressing the actual exception. Fix will be in next release.

ocrmypdf will now return a proper error message in this case. The underlying issue is with pdfminer.six, an ocrmypdf dependency. The file has an unusual, but I don't believe invalid, page tree. It's actually possible for pikepdf (or qpdf) to correct this error, but that will impact performance for the overwhelming majority of files that don't need repair.

Please report the issue to pdfminer.six - they will likely need the attachment as well. Calling `PDFPages.get_pages(...pagenos=[1]...)` should produce an empty iterator instead of the parsed page.

**Closed** 2021-01-10 10:32 UTC
