### ISSUE TITLE
Splitting pages with unpaper-args

### ISSUE THREAD

**Issue by githubnavigator** [jbarlow83/OCRmyPDF#393] opened 2019-05-23 23:17 UTC
In trying to use unpaper-args to split a double-page layout into two pages, the following commands have failed (error listed below) on two different machines:

```
1. ocrmypdf --clean --unpaper-args '-op 2' in.pdf out.pdf
2. ocrmypdf --clean --unpaper-args "-op 2" in.pdf out.pdf 
3. ocrmypdf --clean --unpaper-args '--output-pages 2' in.pdf out.pdf 
4. ocrmypdf --clean --unpaper-args "--output-pages 2" in.pdf out.pdf 
5. ocrmypdf --clean --unpaper-args '--layout double --output-pages 2' in.pdf out.pdf 
6. ocrmypdf --clean --unpaper-args '--layout double -op 2' in.pdf out.pdf 
```
When failing, no errors appear until the following lines, and I am returned to the command prompt:

```
  ERROR - Error occurred while running this command:
(Command '['unpaper', '-v', '--dpi', '300.0', '-op', '2', '/var/folders/nh/dhs1xnss20dd2q0f02yq4k_r0000gn/T/tmp72qcbozv/input.ppm', '/var/folders/nh/dhs1xnss20dd2q0f02yq4k_r0000gn/T/tmp72qcbozv/output.ppm']' returned non-zero exit status 1.)
  ERROR - Error occurred while running this command:
(Command '['unpaper', '-v', '--dpi', '300.0', '-op', '2', '/var/folders/nh/dhs1xnss20dd2q0f02yq4k_r0000gn/T/tmp6l3qsq7c/input.ppm', '/var/folders/nh/dhs1xnss20dd2q0f02yq4k_r0000gn/T/tmp6l3qsq7c/output.ppm']' returned non-zero exit status 1.)
  ERROR - Error occurred while running this command:
(Command '['unpaper', '-v', '--dpi', '300.0', '-op', '2', '/var/folders/nh/dhs1xnss20dd2q0f02yq4k_r0000gn/T/tmpo1mj_y_j/input.ppm', '/var/folders/nh/dhs1xnss20dd2q0f02yq4k_r0000gn/T/tmpo1mj_y_j/output.ppm']' returned non-zero exit status 1.)
  ERROR - Error occurred while running this command:
(Command '['unpaper', '-v', '--dpi', '300.0', '-op', '2', '/var/folders/nh/dhs1xnss20dd2q0f02yq4k_r0000gn/T/tmpxaw47uvr/input.ppm', '/var/folders/nh/dhs1xnss20dd2q0f02yq4k_r0000gn/T/tmpxaw47uvr/output.ppm']' returned non-zero exit status 1.)
```
('-op' is '--output-pages' when I try to use that variant instead.)

However, the following command runs successfully: 

`ocrmypdf --clean --unpaper-args '--layout double' in.pdf out.pdf`

Any ideas?

-happens on both Ubuntu 18 and macOS
-fresh install today on both machines through pip3 (version 8.3.0, unpaper version 6.1)
-happens 100% of the time, regardless of the software that creates the PDF, the PDF length, and the content of the PDF

**Comment by jbarlow83** [comment] 2019-05-24 06:00
While it is possible to use `--layout double` to tell unpaper to expect an image that can contains two pages, but it's not possible to actually the split into independent pages. (This is mentioned as a caveat in the documentation.) The end result is that the text on the two pages should be independently cleaned up, but you still get one PDF page with two logical pages.

I don't currently have a way to deal with an image processing command that does anything other than one image in, one image out. I go to great lengths to preserve the original appearance and content of the input PDF whenever possible, and clearly that isn't possible when the page count and layout is reworked. 

You can drop the `-op 2` argument and it should work, although may not exactly what you want.

You could rasterize the pages with Ghostscript, unpaper them, repack as a PDF using img2pdf, and run ocrmypdf on the result.

**Comment by sojusnik** [comment] 2019-06-03 13:01
@githubnavigator Meanwhile you could use the approach with `mutools` as described [here](https://github.com/jbarlow83/OCRmyPDF/issues/330).

I assume, that `unpaper` approach could work, if [this](https://github.com/jbarlow83/OCRmyPDF/issues/392#issuecomment-496831540) gets implemented.

**Comment by jbarlow83** [comment] 2019-06-04 09:03
Duplicate of  #380

**Closed by jbarlow83** 2019-06-04 09:03 UTC
Labels: enhancement
