### ISSUE TITLE
Unable to use on termux

### ISSUE THREAD

**Issue by tathastu871** [jbarlow83/OCRmyPDF#768] opened 2021-04-22 02:48 UTC
**Describe the bug**
What's the problem?
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.9/lib-dynload/_multiprocessing.cpython-39.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 359, in run_pipeline
    pdfinfo = get_pdfinfo(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 155, in get_pdfinfo
    return PdfInfo(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 834, in __init__
    self._pages = _pdf_pageinfo_concurrent(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 620, in _pdf_pageinfo_concurrent
    exec_progress_pool(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 93, in exec_progress_pool
    log_queue: multiprocessing.Queue = multiprocessing.Queue(-1)
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/context.py", line 103, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/queues.py", line 40, in __init__
    from .synchronize import SEM_VALUE_MAX as maxsize
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
```
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
What did you expected to happen?

**Screenshots**

**System (please complete the following information):**
 - OS:
 - Python version:
 - OCRmyPDF version:

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip?

**Additional context**

,

**Comment by jbarlow83** [comment] 2021-04-22 06:05
Thanks for the report. This is a duplicate of #760 .

**Closed by jbarlow83** 2021-04-22 06:05 UTC
