### ISSUE TITLE
WARNING - Output file is okay but is not PDF/A (seems to be No PDF/A metadata in XMP)

### ISSUE THREAD

**Issue by wpzdm** [jbarlow83/OCRmyPDF#490] opened 2020-02-15 10:20 UTC
**Describe the issue**
When I get this warning, the file size is usually larger than I expected. Also in the output is `INFO - Optimize ratio: 3.60 savings: 72.2%`, this is near the expectation. So I think the problem is the failure to convert to PDF/A.

**To Reproduce**

```bash
ocrmypdf --tesseract-timeout=0 --optimize 3 --skip-text --jbig2-lossy kolmbook-eng-scan.pdf kolmbook-eng-scan.o3.pdf 
```
Console output:
```
Scan: 100%|█████████████████████████████████| 519/519 [00:24<00:00, 21.52page/s]
   INFO - Start processing 4 pages concurrent
OCR: 100%|██████████████████████████████| 519.0/519.0 [00:21<00:00, 24.00page/s]
JPEGs: 100%|███████████████████████████████████| 3/3 [00:01<00:00,  2.59image/s]
PNGs: 0image [00:00, ?image/s]
JBIG2: 100%|██████████████████████████████████| 52/52 [00:16<00:00,  3.15item/s]
   INFO - Optimize ratio: 3.60 savings: 72.2%
WARNING - Output file is okay but is not PDF/A (seems to be No PDF/A metadata in XMP)
```

**Example file**
http://www.lirmm.fr/~ashen/kolmbook-eng-scan.pdf
- [x] This is the input file
- [x] The file contains no personal or confidential information
- [ ] I am the copyright holder for this file
- [ ] I permit this file to be included in the OCRmyPDF test suite under the CC-BY-SA 4.0 license
- [ ] I am not the copyright holder, but this file is available under a free software license

**System:**

- OS: macOS 10.14.5
- OCRmyPDF Version: 9.5.0

**Comment by jbarlow83** [comment] 2020-02-18 10:21
Please try running the same command in debug mode (`-v1`).

That will give more information about what Ghostscript was doing.

**Comment by jbarlow83** [comment] 2020-02-18 10:37
Running with `-v1` relays the following error from Ghostscript:

```
GPL Ghostscript 9.50: 
 **** A font missing from the input PDF has been substituted with a different font.
        Widths may differ, reverting to normal PDF output!
```

Because of this missing information in an embedded font, it is not possible to convert this file to PDF/A, except by rasterizing all content to images (`--force-ocr`).

**Comment by wpzdm** [comment] 2020-02-19 03:53
I tried `--force-ocr` on this and several other files. There is no this warning now. 
But the file size is only slightly smaller than using `--skip-text`. Can you think of other possible reasons for this?

**Comment by jbarlow83** [comment] 2020-02-19 04:07
No, I don't see any reason to doubt Ghostscript here.

**Comment by jbarlow83** [comment] 2020-02-19 07:43
Oh, you probably meant why the file didn't compress as well with `--force-ocr`.

`--force-ocr` creates an image of all pages and then OCRs the image. This almost always makes files larger than those that use fonts, even with lossy JBIG2.

**Comment by wpzdm** [comment] 2020-02-19 09:52
Yes, I would like to know how to compress the size in this case. Do you have any other suggestions?

Thanks again.

**Comment by jbarlow83** [comment] 2020-03-02 07:44
PDF/A is supposed to make a file that is reproducible when extraterrestrial archaeologists try to digest the remains of human civilization a million years from now. Because of that, substituted fonts are not acceptable in PDF/A, and there is no way to guarantee that the PDF will appear the same to all users. If you do `--force-ocr` then you accept the larger file size and accept the font substitutions performed by Ghostscript (may be wrong), and the result is PDF/A.

You could try Acrobat DC to see if it can embed the missing fonts into the PDF. It does have features like this.

**Comment by jbarlow83** [comment] 2020-03-23 06:19
I'll close the issue now as I do not believe there is any way to fix it. If you have further related questions feel free to reopen it.

**Closed by jbarlow83** 2020-03-23 06:19 UTC
