### ISSUE TITLE
[Clarification request] Can OCRmyPDF be modified to also create a plain text output file ?

### ISSUE THREAD

**Issue by Wikinaut** [jbarlow83/OCRmyPDF#126] opened 2017-01-19 22:55 UTC
OCRmyPDF's main task is the creation of an mixed-mode (image, text) PDF.

Can OCRmyPDF create a single plain text output file (in addition to the pdf output) ? (One could use `pdftotext`, but this requires a further call).

`tesseract`by its own already can create pdf, hocr and text in one go, and for certain applications like creation of an ebook ( out.txt as input to `calibre` ), this can be useful.

**Comment by jbarlow83** [comment] 2017-01-20 00:42
It could be modified to do this. I could be persuaded but I'm reluctant to add this because `pdftotext` does a decent job. Other than saving typing what's the benefit?

This shell pipeline gets you both:

```bash
ocrmypdf input.pdf - | tee output.pdf | pdftotext - output.txt
```

(Although in the most recent release it sometimes fails because stdout is not flushed correctly. That will be fixed.)

**Comment by Wikinaut** [comment] 2017-02-07 17:52
Coming back to text extraction (for epub generation).

I found that plain text results via `ocrmypdf -> pdftotext` are really useless (text is garbled), whereas the generation via tesseract (alone) is really perfect.

Later this month I can present you some detailed examples, if you want, currently I cannot.

To make sure: I am in favour of using your code, but currently my own tool chain gives much better text file results. Perhaps the problem is pdftotext, which garbles the text, and my original idea of this issue is worth to be resconsidered (ocrmypdf -> text output).

**Comment by jbarlow83** [comment] 2017-02-07 18:05
Is it this issue?

https://github.com/tesseract-ocr/tesseract/issues/357

https://bugs.ghostscript.com/show_bug.cgi?id=696874. (See especially
comment 4. My initial guess at the cause was way off.)

Use --output-type pdf

Ghostscript 9.20 might help if using the default --output-type pdfa

**Comment by Wikinaut** [comment] 2017-02-07 18:12
I used what I wrote here https://github.com/jbarlow83/OCRmyPDF/issues/124#issuecomment-272994801 (without the --debug-rendering), with the old debian 8 ghostscript.

I installed a recent debian 9 with ghostscript 9.20 and can retry it there (in some days).

**Comment by jbarlow83** [comment] 2017-02-07 21:36
Can you send me the file?

`--output-type pdf` disables Ghostscript, so something may be the cause.

**Comment by jbarlow83** [comment] 2017-02-15 21:15
This ended up leading into tesseract issue #712, in which we dramatically improved tesseract PDFs after they pass through Ghostscript. Some viewers still have problems with Tesseract PDFs and it's unlikely that will ever be completed solved. 

Because of that Tesseract PDF conversion can be thought of as a possibly lossy operation with respect to word breaks. Tesseract knows more than it can put in a PDF about where word breaks are located, because of PDF limitations, so it is more reliable to get this out of tesseract directly. 

I'll add the feature.

**Comment by jbarlow83** [comment] 2017-05-12 22:30
Added in v5

**Closed by jbarlow83** 2017-05-12 22:30 UTC
Labels: enhancement
