### ISSUE TITLE
Intermittent tesseract failure (tesseract returns -9/bad file descriptor)

### ISSUE THREAD

**Issue by mritzmann** [jbarlow83/OCRmyPDF#109] opened 2016-11-29 15:01 UTC
Sometimes i get a error with OCRmyPDF.

Distributions: `Ubuntu 16.10 x64`
Memory: `512 MB`
Location: `digitalocean.com (FRA1)`

Input:
`ocrmypdf scan0_161129-144058.pdf scan1_161129-144058.pdf -v 1 &> /home/ocr/log_ocr`

Output:
https://gist.github.com/mritzmann/bfb7298fd14427c282b8a702547c74d5

Testfile:
[scan0_161129-144058.pdf](https://github.com/jbarlow83/OCRmyPDF/files/619297/scan0_161129-144058.pdf)

It works fine in 9 from 10 tests.

**Comment by jbarlow83** [comment] 2016-11-29 23:46
Are you using the Ubuntu 16.10 version of OCRmyPDF (4.2.2) or a more recent version? `ocrmypdf --version`

Since it's non-deterministic and I haven't been able to reproduce, I'll need your help to explore a few things to help narrow the problem.

Run `ocrmypdf -k scan0_161129-144058.pdf scan1_161129-144058.pdf -v 1` and it will print the name of the temporary folder where intermediate files go. The log says it failed running tesseract on 00001.pp-clean.png. I'm curious if there is any difference in that input on runs that fail compared to those that succeed.

I'm curious if there's a difference in 00001.pp-clean.png on runs that fail or succeed.

Could you also try running the same tesseract command in a loop on its own to see if it fails?
```
tesseract -l eng 00001.pp-clean.png 00001.badxml hocr
```

Thanks

**Comment by jbarlow83** [comment] 2017-01-04 21:47
I had a look at this again and saw you only have 512 MB. My guess is that ocrmypdf/Tesseract occasionally needs more memory than this. It could also be that the server has a low limit on the number of file descriptors.

**Comment by jbarlow83** [comment] 2017-01-04 21:48
Marking this as likely on your end, but feel free to reopen if you have any new information.

**Closed by jbarlow83** 2017-01-04 21:47 UTC
