### ISSUE TITLE
OCR Confidence (add --sidecar-hocr)

### ISSUE THREAD

**Issue by alexanderAnexsys** [jbarlow83/OCRmyPDF#273] opened 2018-06-26 11:24 UTC
Is there a way to get the confidence per page or document?

**Comment by jbarlow83** [comment] 2018-06-27 00:02
An important thing to recognize is without ground truth to compare to, Tesseract can be both very confident and very wrong if it happens to be undertrained on your input. Confidence only comes into play when it finds multiple seeming valid ways to interpret an image.

If you use generate the HOCR files (`--pdf-renderer hocr) and keep the temporaries (`-k`) you can parse the generated .hocr files to get this information. I will eventually add a feature to generate .hocr as a sidecar similar to the `--sidecar` feature, but it won't happen in my pending release.

https://stackoverflow.com/questions/37038045/how-to-get-tesseract-confidence-levels-in-python-or-command-window

**Comment by SpencerRP** [comment] 2021-07-13 17:26
Close this or merge with https://github.com/jbarlow83/OCRmyPDF/issues/177

**Comment by jbarlow83** [comment] 2021-07-13 19:10
Duplicate of #177

**Closed by jbarlow83** 2021-07-13 19:10 UTC
