### ISSUE TITLE
Overprint Mode 1 not permitted in PDF/A-2

### ISSUE THREAD

**Issue by djdanielsson** [jbarlow83/OCRmyPDF#703] opened 2020-12-27 20:14 UTC
**Describe the bug**
I am getting "GPL Ghostscript 9.53.3: Setting Overprint Mode to 1 not permitted in PDF/A-2, overprint mode not set" error

**System (please complete the following information):**
 - OS: Fedora 33
 - Python version: 3.9.1
 - OCRmyPDF version: 11.3.3

I saw there were isssues about this in the past, this is my first time trying to use this software. I am just running ocrmypdf -d -s old.pdf new.pdf

**Comment by jbarlow83** [comment] 2020-12-28 00:22
In the vast majority of cases the error is harmless for scanned PDFs. It's an issue for print production PDFs. See https://en.wikipedia.org/wiki/Overprinting

Currently the behavior is that, if Ghostscript reports an error we log the entire stderr, which may include the overprint messages. Otherwise, you'd only see them if you run with debug messages enabled. So probably, the file had other errors or perhaps you ran into some new behavior, but I'd need a test file to see.

**Comment by djdanielsson** [comment] 2020-12-28 02:01
this was all the output given, I do not see any other errors. It's a large pdf I do not know how to split it up but you can download it https://www.dropbox.com/s/fqo1ksbneqvcpi9/Doctrinal_Theology_FACover.pdf 

Scanning contents: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 707/707 [00:01<00:00, 702.92page/s]
Start processing 4 pages concurrently
    2 page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.                                                                         
   18 page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.                                                                         
   21 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
   22 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
   24 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
   23 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
   25 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
   26 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
   30 page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.                                                                         
   28 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
   27 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
   37 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
   44 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
   50 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
   74 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
   84 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
   88 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
   89 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
  126 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
  134 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
  136 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
  145 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
  163 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
  178 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
  196 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
  205 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
  217 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
  273 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
  355 skipping all processing on this page                                                                                                                                                                                                    
  427 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
  436 skipping all processing on this page                                                                                                                                                                                                    
  464 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
  553 skipping all processing on this page                                                                                                                                                                                                    
  633 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
  680 page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.                                                                         
  682 page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.                                                                         
  691 [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                                                                      
  707 page has no images - skipping all processing on this page to avoid losing detail. Use --force-ocr if you wish to perform OCR on pages that have vector content.                                                                         
OCR: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 707.0/707.0 [40:09<00:00,  3.41s/page]
Postprocessing...
GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.53.3: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set


SubprocessOutputError: Ghostscript PDF/A rendering failed

**Comment by jbarlow83** [comment] 2021-01-01 00:34
I was not able to reproduce this with ocrmypdf 11.4.3 or 11.3.4.

That is a very large file and you might get strange errors if you run out of /tmp disk space or system memory. All of the temporary files would take up several GB.

**Comment by djdanielsson** [comment] 2021-01-02 04:32
Upgrading versions fixed the issue, thank you so much. Is there a way to write the pdf with just the text and not the image? I didn't see anything in the command options that seemed to do this.

**Comment by jbarlow83** [comment] 2021-01-02 05:03
Possible `--sidecar` (just text, as a text file) or `--pdf-renderer hocrdebug`. Not all PDFs have an image, they can have mixed vector and raster content on a page or within a file, and ocrmypdf supports this general case. Because of this there isn't an automatic way to get just text. The presentation of OCR text is not always pretty - if it misidentifies things the result will look like a ransom note.

**Comment by jbarlow83** [comment] 2021-01-02 05:03
I'll close the issue now. If you have further related questions feel free to reopen it.

**Closed by jbarlow83** 2021-01-02 05:03 UTC
Labels: user config
