### ISSUE TITLE
How to skip certain pages? - (because Tesseract crashes on a certain page)

### ISSUE THREAD

**Issue by werunom** [jbarlow83/OCRmyPDF#317] opened 2018-11-28 02:31 UTC
Hello! Thanks for this useful software. I have a question which has been partially asked [here](https://github.com/jbarlow83/OCRmyPDF/issues/302). In the conversation of that issue since the question I am interested in has not been directly answered, I thought of bringing it up again. 

Is it possible to skip certain pages while doing the ocr of a book? I have a book (downloaded from [libgen](http://lib1.org/_ads/B4078B7CE5DC19EDBE51D0B5A3DAC8DD)). While running the `ocrmypdf` command, the log shows an error:

```
....
WARNING -  291: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  296: [tesseract] lots of diacritics - possibly poor OCR
  ERROR -  300: [tesseract] contains_unichar_id(unichar_id):Error:Assert failed:in file ../../src/ccutil/unicharset.h, line 502
WARNING -  308: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  355: [tesseract] lots of diacritics - possibly poor OCR
....
```

And at the end, the ocr command unsuccessfully ends by giving this error ---
```
 ERROR - Error occurred while running this command:
(Command '['tesseract', '-l', 'eng', '-c', 'textonly_pdf=1', '/tmp/com.github.ocrmypdf.dh4pkwle/000300.ocr.png', '/tmp/com.github.ocrmypdf.dh4pkwle/000300.text', 'pdf', 'txt']' died with <Signals.SIGSEGV: 11>.)
```
So, this issue is very similar to the issue-302. So, wanted to know is there a way of skipping a specific page (like in my case, page number 300)?

**Comment by jbarlow83** [comment] 2018-11-28 05:33
There's no way of skipping a specific page, other than removing the offending page from the file and adding it back as I described in the related issue you mentioned.

I was not able to replicate the issue using the PDF you linked to.

You found an input file that crashes Tesseract with a segfault, which is a big deal. That's really interesting, and I want to get to the bottom of that.

What does `tesseract --version` say? 
Could you also provide your command line and `ocrmypdf --version`?

**Comment by jbarlow83** [comment] 2018-11-28 11:51
What command line are you using?

**Comment by werunom** [comment] 2018-11-28 12:58
I used the standard one -- `ocrmypdf <input-file> <output-file>`.

Interestingly, the first file I mentioned above had OCR-text on some pages (I had done for 30 pages few weeks back using masterpdfeditor). So, I used both the commands `--force-ocr` and `--redo-ocr`. Both these commands successfully runs for the first iteration (i.e., `redo-ocr` in the first loop recognized that the 30 pages had ocr and removed it). While doing the ocr process, both the commands failed. 

Anyways, when I used another sample pdf, i used the standard command without any variables.

**Comment by jbarlow83** [comment] 2018-11-28 21:22
Okay, could I get you to run `ocrmypdf -k <input-file> <output-file>` on the original file. `-k` retains temporary files for debugging. After the failure, the location of the tmp folder will be printed.

Then try running Tesseract on the image that failed, which was page 300 of your file, so it should go like this:

```
cd $tmpfolder
tesseract -l eng -c textonly_pdf=1 000300.ocr.png 000300.text pdf txt
```

I expect Tesseract will crash again on that image. If it does, please send me the image ``000300.ocr.png`` and I will see if I can reproduce the crash.

**Comment by werunom** [comment] 2018-11-29 06:04
As you expected, running tesseract command was unsuccessful. The command threw this error
```
tesseract -l eng -c textonly_pdf=1 000300.ocr.png 000300.text pdf txt
Tesseract Open Source OCR Engine v4.0.0 with Leptonica
contains_unichar_id(unichar_id):Error:Assert failed:in file ../../src/ccutil/unicharset.h, line 502
Segmentation fault (core dumped)
```
I am attaching the `000300.ocr.png` here...
![000300 ocr](https://user-images.githubusercontent.com/24664855/49202448-a3b08c80-f3ca-11e8-9635-13f7bb836006.png)

**Comment by jbarlow83** [comment] 2018-11-29 06:35
Thank you. Would you mind reporting the issue to Tesseract and including the input image?

I suspect this error is only triggered by a very particular input. A slightly different image, even just a pixel different, may not trigger it, which is why your other program didn't hit this error even though both use Tesseract.

I could not reproduce the crash so details like your platform, CPU type, etc. may be relevant too.

**Comment by aslakstubsgaard** [comment] 2018-11-29 16:46
i had the same issue with this document https://github.com/openmsr/msr-archive/blob/6b18fc3a0c2b6a472a564ff3e48b4262fabd4131/docs/ORNL-1649.pdf

however the issue was resolved by adding the clean flag '-c' to ocrmypdf, which fits with @werunom's explanation since this would change the image of the troublesome page or pages.

**Comment by jbarlow83** [comment] 2018-11-29 20:08
@werunom You found an image that produces an assertion failure in Tesseract. It so happens that ocrmypdf generates this image from your file. There isn't much I can do it about (I have contributed to Tesseract but not in the affected area), but they would definitely find it interesting. It probably has to do with the equations on the page.

You could also try using a different set of Tesseract training data - e.g. download eng.traineddata https://github.com/tesseract-ocr/tessdata_best ; that would likely give different results too.

I could change ocrmypdf to allow it to carry on even if Tesseract crashes but that doesn't seem like the best idea... seems better to get people's attention that something is wrong.

**Comment by jbarlow83** [comment] 2019-01-22 17:51
Since this is a Tesseract issue there's nothing else I can do.

I'll close the issue now. If you have further related questions feel free to reopen it.

**Closed** 2019-01-22 17:51 UTC

**Comment by AlexD97** [comment] 2019-05-04 12:06
Did you try tesseract-oem mode 1? This solved the issue for me.

**Comment by werunom** [comment] 2019-05-04 14:30
Actually, after couple of updates (of both ocrmypdf and tesseract), things started working fine.
