### ISSUE TITLE
subprocess.CalledProcessError - unpaper - returned non-zero exit status 1

### ISSUE THREAD

**Issue by kenyonit** [jbarlow83/OCRmyPDF#667] opened 2020-11-02 03:09 UTC
Currently running ocrmypdf on Centos 8 and getting the follow error when trying to run "--clean" option:

**Current environment:**
Centos 8 x 64
Python- 3.6.8
ocrmypdf - 11.3.1
ghostscript - 9.25-5
qpdf - 8.2.1
tesseract - 4.1.1
jbig2enc - 0.29
pngquant - 2.12.6
unpaper - 6.1

**Sample file:**
[test.pdf](https://github.com/jbarlow83/OCRmyPDF/files/5472564/test.pdf)

**Example:**
ocrmypdf -l eng --clean test.pdf test_2.pdf

```
Scanning contents: 100%|----| 1/1 [00:00<00:00,  9.49page/s]
OCR:   0%|                                                                                                                                                        | 0.0/1.0 [00:00<?, ?page/s]
An exception occurred while executing the pipeline
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_sync.py", line 190, in exec_page_sync
    page_context, orientation_correction
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_sync.py", line 163, in make_intermediate_images
    clean=options.clean,
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_sync.py", line 105, in preprocess
    image = preprocess_clean(image, page_context)
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_pipeline.py", line 478, in preprocess_clean
    unpaper.clean(input_file, output_file, dpi.x, page_context.options.unpaper_args)
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_exec/unpaper.py", line 129, in clean
    run(input_file, output_file, dpi, unpaper_args)
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_exec/unpaper.py", line 94, in run
    raise e from e
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_exec/unpaper.py", line 90, in run
    stdout=PIPE,
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/subprocess.py", line 54, in run
    proc = subprocess_run(args, env=env, **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['unpaper', '-v', '--dpi', '200.00000000000003', '--layout', 'none', '--mask-scan-size', '100', '--no-border-align', '--no-mask-center', '--no-grayfilter', '--no-blackfilter', '--no-deskew', '/tmp/com.github.ocrmypdf.u1dkc01q/000001_rasterize.png', '/tmp/tmpf03w818a/output.ppm']' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_sync.py", line 367, in run_pipeline
    exec_concurrent(context)
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_sync.py", line 284, in exec_concurrent
    task_finished=update_page,
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_concurrent.py", line 112, in exec_progress_pool
    result = results.next()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
subprocess.CalledProcessError: Command '['unpaper', '-v', '--dpi', '200.00000000000003', '--layout', 'none', '--mask-scan-size', '100', '--no-border-align', '--no-mask-center', '--no-grayfilter', '--no-blackfilter', '--no-deskew', '/tmp/com.github.ocrmypdf.u1dkc01q/000001_rasterize.png', '/tmp/tmpf03w818a/output.ppm']' returned non-zero exit status 1.
```

**Comment by kenyonit** [comment] 2020-11-02 04:39
Upon further investigation, I suspect this maybe an issue with unpaper not being able to detect .png files correctly

**Comment by jbarlow83** [comment] 2020-11-02 04:54
Run with --keep-temporary-files, then try running the same unpaper command
ocrmypdf is running as reported in the error message.

**Comment by kenyonit** [comment] 2020-11-02 07:06
It seems that PNG files are not being processed correct, I think unpaper is not picking up the right codec? Could be an issue with ffmpeg (or libav?)

unpaper -vv --layout none --mask-scan-size 100 --no-border-align --no-mask-center --no-grayfilter --no-blackfilter --no-deskew /tmp/com.github.ocrmypdf.x1jk0gr6/000001_rasterize.png /tmp/tmp_ohqkxas/output.ppm
unpaper 6.1
License GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

-------------------------------------------------------------------------------
Processing sheet #1: /tmp/com.github.ocrmypdf.x1jk0gr6/000001_rasterize.png -> /tmp/tmp_ohqkxas/output.ppm
loading file /tmp/com.github.ocrmypdf.x1jk0gr6/000001_rasterize.png.
[aac @ 0xb69d60] Format detected only with low score of 1, misdetection possible!
[aac @ 0xb6af40] More than one AAC RDB per ADTS frame is not implemented. Update your Libav version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0xb6af40] Error decoding AAC frame header.
[aac @ 0xb6af40] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0xb6af40] More than one AAC RDB per ADTS frame is not implemented. Update your Libav version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0xb6af40] Error decoding AAC frame header.
[aac @ 0xb6af40] More than one AAC RDB per ADTS frame is not implemented. Update your Libav version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0xb6af40] Error decoding AAC frame header.
[aac @ 0xb6af40] More than one AAC RDB per ADTS frame is not implemented. Update your Libav version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0xb6af40] Error decoding AAC frame header.
[aac @ 0xb69d60] Could not find codec parameters (Audio: aac
      0 channels, fltp, 815 kb/s)
[aac @ 0xb69d60] Estimating duration from bitrate, this may be inaccurate
Input #0, aac, from '/tmp/com.github.ocrmypdf.x1jk0gr6/000001_rasterize.png':
  Duration: 00:00:00.40, bitrate: 815 kb/s
    Stream #0:0: Audio: aac
      0 channels, fltp, 815 kb/s
unpaper: error: unable to open file /tmp/com.github.ocrmypdf.x1jk0gr6/000001_rasterize.png: wrong stream
Try 'man unpaper' for more information.

**Comment by kenyonit** [comment] 2020-11-02 21:36
I've applied the patch, but it appears unpaper cannot find the .pnm file now?

Here is the debug.log:

[2020-11-03 07:31:40,013] - ocrmypdf.helpers -   DEBUG - pikepdf mmap disabled
[2020-11-03 07:31:40,013] - ocrmypdf.helpers -   DEBUG - os.symlink(test.pdf, /tmp/com.github.ocrmypdf.5viez1ln/origin)
[2020-11-03 07:31:40,014] - ocrmypdf.helpers -   DEBUG - os.symlink(/tmp/com.github.ocrmypdf.5viez1ln/origin, /tmp/com.github.ocrmypdf.5viez1ln/origin.pdf)
[2020-11-03 07:31:40,022] - ocrmypdf.helpers -   DEBUG - pikepdf mmap disabled
[2020-11-03 07:31:40,127] - ocrmypdf.builtin_plugins.tesseract_ocr -   DEBUG - Using Tesseract OpenMP thread limit 1
[2020-11-03 07:31:40,140] - ocrmypdf.helpers -   DEBUG - pikepdf mmap disabled
[2020-11-03 07:31:40,145] - ocrmypdf._pipeline -   DEBUG -    1  Rasterize with png16m, rotation 0
[2020-11-03 07:31:40,146] - ocrmypdf.subprocess -   DEBUG -    1  Running: ['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-sDEVICE=png16m', '-dFirstPage=1', '-dLastPage=1', '-r200.000000x200.000000', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/com.github.ocrmypdf.5viez1ln/origin.pdf']
[2020-11-03 07:31:40,601] - ocrmypdf.subprocess.subprocess.gs -   DEBUG -    1  stderr = jbig2dec WARNING File has an invalid segment data length! Trying to decode using the available data. (segment 0x01)

[2020-11-03 07:31:40,602] - ocrmypdf._exec.ghostscript -   DEBUG -    1  jbig2dec WARNING File has an invalid segment data length! Trying to decode using the available data. (segment 0x01)

[2020-11-03 07:31:40,608] - ocrmypdf._exec.ghostscript -   DEBUG -    1  Rotating output by 0
[2020-11-03 07:31:40,903] - ocrmypdf.subprocess -   DEBUG -    1  Running: ['unpaper', '-v', '--dpi', '200.00000000000003', '--layout', 'none', '--mask-scan-size', '100', '--no-border-align', '--no-mask-center', '--no-grayfilter', '--no-blackfilter', '--no-deskew', '/tmp/tmpahplx3v3/input.pnm', '/tmp/tmpahplx3v3/output.ppm']
[2020-11-03 07:31:40,923] - ocrmypdf.subprocess.subprocess.unpaper -   DEBUG -    1  stdout/stderr = unpaper: error: unable to open file /tmp/tmpahplx3v3/input.pnm: Invalid data found when processing input
Try 'man unpaper' for more information.
unpaper 6.1
License GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

-------------------------------------------------------------------------------
Processing sheet #1: /tmp/tmpahplx3v3/input.pnm -> /tmp/tmpahplx3v3/output.ppm

[2020-11-03 07:31:40,954] - ocrmypdf._sync -   ERROR - An exception occurred while executing the pipeline
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_sync.py", line 190, in exec_page_sync
    page_context, orientation_correction
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_sync.py", line 163, in make_intermediate_images
    clean=options.clean,
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_sync.py", line 105, in preprocess
    image = preprocess_clean(image, page_context)
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_pipeline.py", line 478, in preprocess_clean
    unpaper.clean(input_file, output_file, dpi.x, page_context.options.unpaper_args)
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_exec/unpaper.py", line 124, in clean
    run(input_file, output_file, dpi, unpaper_args)
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_exec/unpaper.py", line 90, in run
    logs_errors_to_stdout=True,
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/subprocess.py", line 63, in run
    proc = subprocess_run(args, env=env, **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['unpaper', '-v', '--dpi', '200.00000000000003', '--layout', 'none', '--mask-scan-size', '100', '--no-border-align', '--no-mask-center', '--no-grayfilter', '--no-blackfilter', '--no-deskew', '/tmp/tmpahplx3v3/input.pnm', '/tmp/tmpahplx3v3/output.ppm']' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_sync.py", line 367, in run_pipeline
    exec_concurrent(context)
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_sync.py", line 284, in exec_concurrent
    task_finished=update_page,
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/_concurrent.py", line 112, in exec_progress_pool
    result = results.next()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
subprocess.CalledProcessError: Command '['unpaper', '-v', '--dpi', '200.00000000000003', '--layout', 'none', '--mask-scan-size', '100', '--no-border-align', '--no-mask-center', '--no-grayfilter', '--no-blackfilter', '--no-deskew', '/tmp/tmpahplx3v3/input.pnm', '/tmp/tmpahplx3v3/output.ppm']' returned non-zero exit status 1.

**Comment by kenyonit** [comment] 2020-11-02 22:13
Actually looks like it can find the file, however experiencing an issue with unpaper: error: unable to open file /tmp/tmpahplx3v3/input.pnm: Invalid data found when processing input

**Comment by jbarlow83** [comment] 2020-11-03 09:59
Try modifying ocrmypdf to save a copy of the pnm file and see if unpaper works on that.

I cannot reproduce this on my system and creating a functional OCRmyPDF on CentOS 8 would be a huge effort. Since unpaper does not seem to be available on CentOS 8, I assume you're compiling it along with many dozen other packages from source, and this may be a reason things are not working. It's also possible that jbig2dec is miscompiled...
```
jbig2dec WARNING File has an invalid segment data length! Trying to decode using the available data. (segment 0x01)
```
(that does not occur on current versions of jbig2dec). I take that to mean ghostscript/jbig2dec produce invalid data which ocrmypdf passes on to unpaper.

**Comment by jbarlow83** [comment] 2020-11-03 10:00
That said, I did end up fixing a few other issues while exploring this one so it was helpful contribution to open this issue.

**Comment by Ubuntufanboy** [comment] 2021-10-01 10:40
I would try rebooting or updating the modules if possible

**Comment by jbarlow83** [comment] 2021-11-15 07:01
Closing issue to age/obscurity

**Closed by jbarlow83** 2021-11-15 07:01 UTC
Labels: user config
