### ISSUE TITLE
[Question] How to OCR rotated pages?

### ISSUE THREAD

**Issue by andrei-volkau** [jbarlow83/OCRmyPDF#695] opened 2020-12-15 17:16 UTC
**Question:** Is it possible to automatically detect that a PDF document consists of vertical scans and to OCR it correctly?

I mean a document like the following one.
[Reader - LJM_-419-430.pdf](https://github.com/jbarlow83/OCRmyPDF/files/5697436/Reader.-.LJM_-419-430.pdf)

I was able to run the document through the OCRmyPDF tool. I am sending the result.
[Reader - LJM_+OCR-419-430.pdf](https://github.com/jbarlow83/OCRmyPDF/files/5697448/Reader.-.LJM_%2BOCR-419-430.pdf)

I believe that the tool expects horizontal text. So the tool was not able to recognize the text correctly. 

Thank you in advance for any hints!

**Comment by jbarlow83** [comment] 2020-12-15 22:10
You can try `--rotate-pages` to attempt rotation before OCR. You may also need `--rotate-pages-threshold` to rotate more readily (may also create false positives).

**Comment by andrei-volkau** [comment] 2020-12-17 12:51
Hi @jbarlow83 ,

Thank you very much for the hint! 

I got the point that `--rotate-pages `automatically rotate pages based on detected text orientation.

I decided to use the default threshold. So the very first page in my document was not rotated. Probably, the heuristic was not confident enough to apply the orientation.

[rotated.pdf](https://github.com/jbarlow83/OCRmyPDF/files/5709464/rotated.pdf)

Could you point me to the piece of code that is responsible for that heuristic, please?

**Comment by jbarlow83** [comment] 2020-12-22 08:56
The rotation is performed by running Tesseract: `tesseract --psm 0 input.png stdout`. Tesseract in turn used a neural network which is trained to recognize orientations.

https://github.com/tesseract-ocr/tesseract

I'll close this because it sounds like the issue is resolved.

**Closed by jbarlow83** 2020-12-22 08:56 UTC

**Comment by andrei-volkau** [comment] 2020-12-22 09:02
@jbarlow83 Thank you very much for the info!
