### ISSUE TITLE
PDF/A-1B fails validation by veraPDF

### ISSUE THREAD

**Issue by so-o** [jbarlow83/OCRmyPDF#693] opened 2020-12-14 02:56 UTC
The objective is to convert a PDF generated by Firefox into a PDF/A-1B.

```
$ ocrmypdf --output-type pdfa-1 --optimize 0 --skip-text --tesseract-timeout 0 file.pdf pdfa.pdf
Scanning contents: 100%|████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 69.88page/s]
Start processing 2 pages concurrently
    1 skipping all processing on this page                                                                                          
    2 skipping all processing on this page                                                                                          
Image processing: 100%|████████████████████████████████████████████████████████████████████████| 2.0/2.0 [00:00<00:00, 165.56page/s]
Postprocessing...
Output file is a PDF/A-1B (as expected)
```
veraPDF has a complaint:

```
$ verapdf -v --format text -f 1b pdfa.pdf
FAIL 6.7.3-1
```

The error code is explained here: https://docs.verapdf.org/validation/pdfa-part1. Search for 6.7.3-1 in the page.

OCRmyPDF : 11.3.3
veraPDF: 1.16.1
gs: 9.50

The original PDF output by Firefox, just text, no images:

[legal_en.pdf](https://github.com/jbarlow83/OCRmyPDF/files/5686172/legal_en.pdf)

**Comment by jbarlow83** [comment] 2020-12-14 03:14
This is probably fixed with pikepdf 2.2.1. Please update to the latest versions of ocrmypdf and pikepdf.

**Comment by so-o** [comment] 2020-12-18 10:16
With OCRmyPDF 11.4 installed from github, if I install pikepdf 2.2.1 (dev), also from github, the command ocrmypdf coredumps. No problem with pikepdf 2.2.0, except that a PDF/A-1B isn't validated by veraPDF.

**Comment by jbarlow83** [comment] 2020-12-18 12:22
Please report entirely new issues (such as core dump) by opening a new
issue with steps to reproduce, error messages, and details about your
platform that the new issue template requests. Otherwise, I can only guess
what the issue is, and that will waste both of our time.

**Closed** 2020-12-19 23:13 UTC
